# Generated by Django 5.0.3 on 2024-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjCode', models.CharField(max_length=10)),
                ('subjName', models.CharField()),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('classRoom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahe_id', models.CharField(default='MAHE0000000', max_length=15, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
