# Generated by Django 5.0.3 on 2024-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjCode', models.CharField(max_length=10)),
                ('subjName', models.CharField()),
                ('startDate', models.CharField()),
                ('startTime', models.CharField()),
                ('endTime', models.CharField()),
                ('classRoom', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
