# Generated by Django 5.0.3 on 2024-03-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='mahe_id',
            field=models.CharField(null=True),
        ),
    ]
