# Generated by Django 5.0.3 on 2024-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_exam_mahe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subjCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
